import React from 'react'
import styled from 'styled-components'
import { FaFile , FaFileAlt} from "react-icons/fa";


export default function GistBody({createdDate , updatedDate}) {
  return (
   <>
   <Wrapper>
    <TextWrapper>
        Created at: 12/02/2023{createdDate}
    </TextWrapper>
    <TextWrapper style={{marginLeft: 15}}>
        Last Updated: 12/02/2023{updatedDate}
    </TextWrapper>
   </Wrapper>
   <Wrapper>
    <BodyWrapper>
        Generated By SiossMaster.com
    </BodyWrapper>
   </Wrapper> 
   <Wrapper>
    <TextWrapper style={{color:'#0265d6'}}>        
        <FaFileAlt style={{marginRight: 5}}/> machine.js
    </TextWrapper>



   </Wrapper>
   </>
  )
}
const Wrapper = styled.div`
   display: flex;
   justify-content: flex-start;
    flex-wrap: wrap;
    align-items: center;
    padding-top: 10px;
`
const TextWrapper = styled.text`
    font-size: 12px;
    font-weight: 400;
    color: #656565;
`
const BodyWrapper = styled.text`
font-size : 15px;
font-weight: 500;
color: #656565;

`